package edots.tasks;

import android.os.AsyncTask;
import android.util.Log;

import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;

import edots.models.Visit;

/**
 * @author lili
 * parameters: patientId, localeID, projectID
 * load the visit group number and the visit number which is generated by the database
 */
public class NewVisitLoadTask extends AsyncTask<String,String,Visit> {
    @Override
    protected Visit doInBackground(String... params) {

        // instantiate patient to be returned
        Visit v = null;

        // setup server parameters
        // TODO: do not hard code in these parameters
        
        final String NAMESPACE = "http://demo.sociosensalud.org.pe/";
        final String URL=NAMESPACE+"EdotsWS/Service1.asmx";
        final String METHOD_NAME = "ListadoGrupoVisitas";
        final String SOAP_ACTION = NAMESPACE+METHOD_NAME;
        SoapObject request = new SoapObject(NAMESPACE, METHOD_NAME);

        request.addProperty("CodigoPaciente", params[0]);
        request.addProperty("CodigoLocal", params[1]);
        request.addProperty("CodigoProyecto", params[2]);

        // create request
        SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        envelope.dotNet = true;

        envelope.setOutputSoapObject(request);

        HttpTransportSE transporte = new HttpTransportSE(URL);
        transporte.debug = true;
        try
        {
            transporte.call(SOAP_ACTION, envelope);

            // get the response as a SoapObject
            SoapObject resSoap = (SoapObject) envelope.getResponse();

            // Get the first row
            SoapObject ic = (SoapObject) resSoap.getProperty(0);

            Log.v("NewVisitLoadTask.java: The visit that we got was", ic.toString());

            // instantiate a new visit to be returned
            v = new Visit(params[1],
                          params[2],
                          ic.getProperty("CodigoGrupoVisita").toString(),
                          ic.getProperty("NombreGrupoVisita").toString(),
                          ic.getProperty("CodigoVisita").toString(),
                          ic.getProperty("DescripcionVisita").toString(),
                          params[0],
                          "date","time","promoter");

            Log.v("NewVisitLoadTask: visit:", v.toString());
        }
        catch (Exception e)
        {
            e.printStackTrace();
            v = null;
        }

        return v;
    }

}

